apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod1
  labels:
    app: test-pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod1
  template:
    metadata:
      labels:
        app: test-pod1
    spec:
      containers:
      - name: test-container
        image: nicolaka/netshoot:latest
        command: ["sleep"]
        args: ["3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        kubernetes.io/hostname: host1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod2
  labels:
    app: test-pod2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod2
  template:
    metadata:
      labels:
        app: test-pod2
    spec:
      containers:
      - name: test-container
        image: nicolaka/netshoot:latest
        command: ["sleep"]
        args: ["3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      nodeSelector:
        kubernetes.io/hostname: host2
---
apiVersion: v1
kind: Service
metadata:
  name: test-service1
  labels:
    advertise: "bgp"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: test-pod1
---
apiVersion: v1
kind: Service
metadata:
  name: test-service2
  labels:
    advertise: "bgp"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: test-pod2
